version: '3'

networks:
  temp: 
    name: temp
    external: true

services:
  sim0: 
    image: zhangbaozhe/ros_nvidia_px4:noetic_simulation
    networks: 
      temp: 
        ipv4_address: 172.18.0.10
    expose: 
      - 5555
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    deploy: 
      resources: 
        limits: 
          cpus: '2'
        reservations: 
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash  -c "cd simulation_ws && bash start.bash 172.18.0.10 0 True"
  mpc0: 
    image: zhangbaozhe/ros_nvidia_px4:noetic_controller
    networks: 
      temp: 
        ipv4_address: 172.18.0.11
    expose: 
      - 5555
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime
      - ./csv/:/simulation_ws/src/control_demo/csv/
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    deploy: 
      resources: 
        limits: 
          cpus: '2'
        reservations: 
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash  -c "cd simulation_ws && bash start.bash 172.18.0.11 1 2.0 1.0"