version: '3.5'
volumes:
  ssh:
  home:
services:
  terminalserver:
    image: ros_xrdp:ubuntu-20.04
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - home:/home/

