version: '3'

services:
        w0:
                image: baozhe_mpc:compose
                networks: 
                        - w0
                command: 0 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w1:
                image: baozhe_mpc:compose
                networks: 
                        - w1
                command: 1 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w2:
                image: baozhe_mpc:compose
                networks: 
                        - w2
                command: 2 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w3:
                image: baozhe_mpc:compose
                networks: 
                        - w3
                command: 3 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w4:
                image: baozhe_mpc:compose
                networks: 
                        - w4
                command: 4 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w5:
                image: baozhe_mpc:compose
                networks: 
                        - w5
                command: 5 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w6:
                image: baozhe_mpc:compose
                networks: 
                        - w6
                command: 6 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w7:
                image: baozhe_mpc:compose
                networks: 
                        - w7
                command: 7 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w8:
                image: baozhe_mpc:compose
                networks: 
                        - w8
                command: 8 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w9:
                image: baozhe_mpc:compose
                networks: 
                        - w9
                command: 9 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w10:
                image: baozhe_mpc:compose
                networks: 
                        - w10
                command: 10 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w11:
                image: baozhe_mpc:compose
                networks: 
                        - w11
                command: 11 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w12:
                image: baozhe_mpc:compose
                networks: 
                        - w12
                command: 12 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w13:
                image: baozhe_mpc:compose
                networks: 
                        - w13
                command: 13 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w14:
                image: baozhe_mpc:compose
                networks: 
                        - w14
                command: 14 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w15:
                image: baozhe_mpc:compose
                networks: 
                        - w15
                command: 15 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w16:
                image: baozhe_mpc:compose
                networks: 
                        - w16
                command: 16 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w17:
                image: baozhe_mpc:compose
                networks: 
                        - w17
                command: 17 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w18:
                image: baozhe_mpc:compose
                networks: 
                        - w18
                command: 18 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w19:
                image: baozhe_mpc:compose
                networks: 
                        - w19
                command: 19 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w20:
                image: baozhe_mpc:compose
                networks: 
                        - w20
                command: 20 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w21:
                image: baozhe_mpc:compose
                networks: 
                        - w21
                command: 21 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w22:
                image: baozhe_mpc:compose
                networks: 
                        - w22
                command: 22 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w23:
                image: baozhe_mpc:compose
                networks: 
                        - w23
                command: 23 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w24:
                image: baozhe_mpc:compose
                networks: 
                        - w24
                command: 24 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w25:
                image: baozhe_mpc:compose
                networks: 
                        - w25
                command: 25 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w26:
                image: baozhe_mpc:compose
                networks: 
                        - w26
                command: 26 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w27:
                image: baozhe_mpc:compose
                networks:    
                        - w27
                command: 27 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w28:
                image: baozhe_mpc:compose
                networks: 
                        - w28
                command: 28 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w30:
                image: baozhe_mpc:compose
                networks: 
                        - w30
                command: 30 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w31:
                image: baozhe_mpc:compose
                networks: 
                        - w31
                command: 31 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
        w29:
                image: baozhe_mpc:compose
                networks: 
                        - w29
                command: 29 32 0.05
                volumes:
                        - /home/a210zbz/landing_docker/Docker/build/data:/root/data/ 
                        - /etc/localtime:/etc/localtime
                deploy:
                        resources:
                                limits:
                                        cpus: '4'
networks: 
        w0: 
        w1:
        w2: 
        w3: 
        w4: 
        w5: 
        w6: 
        w7: 
        w8: 
        w9: 
        w10:
        w11:
        w12:
        w13:
        w14:
        w15:
        w16: 
        w17:
        w18: 
        w19: 
        w20: 
        w21: 
        w22: 
        w23: 
        w24: 
        w25: 
        w26: 
        w27: 
        w28: 
        w29: 
        w30: 
        w31: 
